port 7000                        # Listen 7000 port
cluster-enabled yes              # cluster生效
cluster-config-file nodes.conf.  # cluster節點資訊檔名
cluster-node-timeout 5000        # 逾時時間五秒
appendonly yes                   # 記錄每次操作
masterauth pass.123              # 連入本節點的密碼
requirepass pass.123             # 連外部Redis節點的密碼

